[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe" 
# cargo install -f cargo-binutils
# rustup component add llvm-tools-preview
rustflags = ["-C", "target-feature=+crt-static"]

[build]
jobs = 2


